apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../deployment.yaml
- ../application.yaml

commonLabels:
  app: book-api
  app.kubernetes.io/name: book-api
  app.kubernetes.io/part-of: library-system