apiVersion: v1
kind: Secret
metadata:
  name: {{ include "book-library.fullname" . }}
  labels:
    {{- include "book-library.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.env.security.secretKey | default (randAlphaNum 32) | quote }}
  db-user: {{ .Values.env.database.user | quote }}
  db-password: {{ .Values.env.database.password | default (randAlphaNum 16) | quote }}